server:
  port: 8083
spring:
  application:
    name: dianping+xhs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Lyf20040915
  ai:
    openai:
      api-key: sk-85d93a3c1cf64214b95cd9bbfdd13a2a
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
      embedding:
        options:
          model: text-embedding-v3 # 向量模型名称
          dimensions: 1024 # 向量维度，v3默认就是1024，可以不写
    vectorstore:
      redis:
        host: localhost
        port: 6380   # 👈 关键在这里
        index: rag_index #Redis 里向量索引的名字
        prefix: 'rag:' #向量数据的 key 前缀
        initialize-schema: true

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: localhost # 你的虚拟机IP
    port: 5672 # 端口
    listener:
      simple:
        prefetch: 5 # # 每次单个线程只能获取5条消息，处理完成才能获取下一个消息
        acknowledge-mode: manual
        retry:
          enabled: false   # 开启消费者失败重试
          initial-interval: 1000ms # 初始的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval（类似csma-cd）
          max-attempts: 3 # 最大重试次数
          stateless: false # true无状态；false有状态。如果业务中包含事务，这里改为false

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
    org.springframework.ai.chat.client.advisor: debug