---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 16959.
--- DateTime: 2026/2/4 15:03
---
local viewKey = KEYS[1]
local hotKey = KEYS[2]
local tagHotPrefix = KEYS[3]
local interestKey = KEYS[4]

local blogId = ARGV[1]
local expireTime = tonumber(ARGV[2])

local result = redis.call('SADD', viewKey, blogId)

if result == 1 then
    redis.call('EXPIRE', viewKey, expireTime)
    redis.call('ZINCRBY', hotKey, 1, blogId)

    for i = 3, #ARGV do
        local tag = ARGV[i]
        redis.call('ZINCRBY', tagHotPrefix .. tag, 1, blogId)
        redis.call('ZINCRBY', interestKey, 1, tag)
    end
end

return result
