---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ghp.
--- DateTime: 2023/7/15 15:22
--- Description 判断库存是否充足 && 判断用户是否已下单
---同时将用户下单的信息发送到消息队列中，用于后续异步写入数据库
---把“一人一单 + 扣库存”前移到 Redis，并且一次性原子完成  在高并发秒杀场景下，Lua 方案性能和一致性都更好，也是生产环境的主流方案。
---
---
-- 优惠券id
local voucherId = ARGV[1];
-- 用户id
local userId = ARGV[2];
-- 1.3.订单 id
local orderId = ARGV[3]

-- 库存的key ..表示连接符
local stockKey = 'seckill:stock:' .. voucherId;
-- 订单key 用set存储所有已下单的用户id
local orderKey = 'seckill:order:' .. voucherId;

-- 判断库存是否充足 get stockKey > 0 ?
local stock = redis.call('GET', stockKey);
if (tonumber(stock) <= 0) then
    -- 库存不足，返回1
    return 1;
end

-- 库存充足，判断用户是否已经下过单 SISMEMBER orderKey userId
if (redis.call('SISMEMBER', orderKey, userId) == 1) then
    -- 用户已下单，返回2
    return 2;
end

-- 3.4.扣库存 incrby stockKey -1
redis.call('incrby', stockKey, -1)
-- 3.5.下单（保存用户） sadd orderKey userId
redis.call('sadd', orderKey, userId)
--[[-- 3.6.发送消息到队列中：XADD stream.orders * k1 v1 k2 v2 ...
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)]]

-- 返回0，标识下单成功
return 0;
